footerPath: 'src/partials/footer.hbs'
headerPath: 'src/partials/head.hbs'
patternsRoot: 'src/patterns'

baseUrl: "/"
destination: '/public'
data: '/src/data/data.yml'
dataPatterns: '/src/data'
exportData: '/src/data/drupal.yml'
exportDestination: '/export/patterns'

plugins:
  <%= compiler %>:
